#Splash screen properties
#Mon Mar 30 05:30:29 CEST 2026
background=0x87ceeb
bar=0xCB3D35
barBackground=0xFFFFFF
barBorder=0xC0C0C0
enabled=true
font=0x0
fontTexture=textures/font/ascii.png
forgeTexture=fml\:textures/gui/km.gif
logoOffset=0
memoryGood=0x78CB34
memoryLow=0xE42F2F
memoryWarn=0xE6E84A
resourcePackPath=resources
rotate=false
showMemory=true
